### ISSUE TITLE
New feature: hide items

### ISSUE THREAD

**Issue by ArthurBodom** [MSVCode/ror_2_companion#1]
Hi!

Nice app, very useful!

Could you add a new feature for hiding some items in the main list?

### How it would work 
In an item menu, we would have an option "Hide this item"
In the options, we would have a section "Hidden items"

This could be very useful because we don't use all the items (for example: item scraps)

**Comment by ArthurBodom** [comment]
This issue might be obsolete because of the other "New feature: item lists/builds"

**Comment by MSVCode** [comment]
Closed in favor of #2
